# Site settings
title: Creative HotHouse Docs
email: docs@creativehothouse.com
description: > # this means to ignore newlines until "baseurl:"
 Documentation repository
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://creativehothouse.com" # the base hostname & protocol for your site
twitter_username:
github_username:  creativehothouse
credits: © 2015 Creative HotHouse Pte. Ltd.

# Permalinks
permalink:   /:categories/:title/

# Build settings
markdown: kramdown
